### ISSUE TITLE
Can't resolve './src/main.ts'

### ISSUE THREAD

**Issue by D3visionNL** [c0derMo/orakel#1]
Hi,

When I try to run the client I get this error:

`Can't resolve './src/main.ts'`

I tried adding the missing main.ts from the previous commit but got this error in the browser console:

`Uncaught Error: [Vuetify] Could not find defaults instance`

I'd love some help with fixing this cause I am stumped😂

**Comment by c0derMo** [comment]
I think I pushed all the missing files now.

Keep in mind that this project is largely unfinished and currently unmaintained at the moment, due to me not having enough time for this - I might pick it back up at a future point though. :)
